## **第四題：錄取分數表格**

題目說明：小明今年考大學，請你依照 [“國文”, “英文”, “數甲”, “數乙”, “物理”, “化學”, “生物”, “歷史”, “地理”, “公民”] 的順序，輸入他的分數分別是：[86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]，而他所想申請的大學各系採計的科目權重如下：

{
“土語系”: [2, 2, 0, 1, 0, 0, 0, 1, 1, 0],

“財政系”: [1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0],

“金融系”: [1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0],

“國貿系”: [1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0],

“會計系”: [1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0],

“法律系”: [1, 2, 0, 1, 0, 0, 0, 1, 0, 1],

“公行系”: [1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25],

“應數系”: [1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0],

“教育系”: [1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]

}

請幫他做出一個表格，第一欄顯示科系，接下來顯示權重並標示科目，最後一欄顯示加權分數。

In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
score=[86.5, 79.4, 88.2, 96.5, 86.3, 76.8, 96.1, 78.5, 82.4, 88.6]
df=pd.DataFrame(index=['國文', '英文', '數甲', '數乙', '物理', '化學', '生物', '歷史', '地理', '公民'])

df['土語系']=[2, 2, 0, 1, 0, 0, 0, 1, 1, 0]
df['財政系']=[1, 1.5, 0, 1.5, 0, 0, 0, 0, 0, 0]
df['金融系']=[1, 1.5, 0, 2, 0, 0, 0, 0, 0, 0]
df['國貿系']=[1.5, 2, 0, 2, 0, 0, 0, 0, 0, 0]
df['會計系']=[1.5, 2, 0, 2, 0, 0, 0, 1, 1, 0]
df['法律系']=[1, 2, 0, 1, 0, 0, 0, 1, 0, 1]
df['公行系']=[1, 1.5, 0, 1.25, 0, 0, 0, 0, 0, 1.25]
df['應數系']=[1, 1, 1.5, 0, 1, 1, 0, 0, 0, 0]
df['教育系']=[1.5, 2, 0, 1.25, 0, 0, 0, 1, 1, 0]
df2=df.transpose(copy=True)
score2=[]
#score2.append()
#df['加權分數']=[]
a=0
for i in [x*y for x,y in zip(score,df['土語系'])]:
  a+=i
score2.append(a)
a=0
for i in [x*y for x,y in zip(score,df['財政系'])]:
  a+=i
score2.append(a)
a=0
for i in [x*y for x,y in zip(score,df['金融系'])]:
  a+=i
score2.append(a)
a=0
for i in [x*y for x,y in zip(score,df['國貿系'])]:
  a+=i
score2.append(a)
a=0
for i in [x*y for x,y in zip(score,df['會計系'])]:
  a+=i
score2.append(a)
a=0
for i in [x*y for x,y in zip(score,df['法律系'])]:
  a+=i
score2.append(a)
a=0
for i in [x*y for x,y in zip(score,df['公行系'])]:
  a+=i
score2.append(a)
a=0
for i in [x*y for x,y in zip(score,df['應數系'])]:
  a+=i
score2.append(a)
a=0
for i in [x*y for x,y in zip(score,df['教育系'])]:
  a+=i
score2.append(a)
df2['加權分數']=score2
df2

      國文   英文   數甲    數乙   物理   化學   生物   歷史   地理    公民     加權分數
土語系  2.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  1.0  0.00  589.200
財政系  1.0  1.5  0.0  1.50  0.0  0.0  0.0  0.0  0.0  0.00  350.350
金融系  1.0  1.5  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  398.600
國貿系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  0.0  0.0  0.00  481.550
會計系  1.5  2.0  0.0  2.00  0.0  0.0  0.0  1.0  1.0  0.00  642.450
法律系  1.0  2.0  0.0  1.00  0.0  0.0  0.0  1.0  0.0  1.00  508.900
公行系  1.0  1.5  0.0  1.25  0.0  0.0  0.0  0.0  0.0  1.25  436.975
應數系  1.0  1.0  1.5  0.00  1.0  1.0  0.0  0.0  0.0  0.00  461.300
教育系  1.5  2.0  0.0  1.25  0.0  0.0  0.0  1.0  1.0  0.00  570.075